GET http://localhost:7200/products
Content-Type: application/json

###
GET http://localhost:7200/
Content-Type: application/json

###
GET http://localhost:7200/users
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haGVzaCBNYWRkaGkiLCJlbWFpbCI6Im1hZGRpbWFoZXNoMTExQGdtYWlsLmNvbSIsImlhdCI6MTcxMTA5MDM4NywiZXhwIjoxNzExMjYzMTg3fQ.ndm4ZZkM5ZWaVlOFJYYVsCywBbaOCyBgFREhL0J3kBc

###
GET http://localhost:7200/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haGVzaCBNYWRkaGkiLCJlbWFpbCI6Im1hZGRpbWFoZXNoMTExQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2MzkwMiwiZXhwIjoxNzE2NjU1OTAyfQ.J7DGD2F-coPudhYwsAZGO3Ym1DsjKebbVmBU1DW7nPE


###
POST http://localhost:7200/addUser
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234",
    "fullName": "testing123",
    "mobile": "12345123455"
  }
###

POST http://localhost:7200/addToCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haGVzaCBNYWRkaGkiLCJlbWFpbCI6Im1hZGRpbWFoZXNoMTExQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2MzkwMiwiZXhwIjoxNzE2NjU1OTAyfQ.J7DGD2F-coPudhYwsAZGO3Ym1DsjKebbVmBU1DW7nPE

{
    "productId": 102,
    "quantity" : 2
  }

###

###
POST http://localhost:7200/login
Content-Type: application/json

{
   "email": "maddimahesh111@gmail.com",
    "password": "12345"
}
###

###
POST http://localhost:7200/addProductToCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haGVzaCBNYWRkaGkiLCJlbWFpbCI6Im1hZGRpbWFoZXNoMTExQGdtYWlsLmNvbSIsImlhdCI6MTcxMzkzOTE4OCwiZXhwIjoxNzE2NTMxMTg4fQ.BVMQyFtOVzmjPKW6Q4OMs4PQqCPVkjTDDiCuH2RqOkE

{
    "email": "maddimahesh111@gmail.com",
    "productId":402,
    "quantity":4
}
###
POST http://localhost:7200/getProductsOnUserId
Content-Type: application/json

{
    "email" : "mahesh@gmail.com"
}

###

DELETE http://localhost:7200/deleteUser/test@gmail.com
Content-Type: application/json
###
PUT http://localhost:7200/updateUser 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haGVzaCBNYWRkaGkiLCJlbWFpbCI6Im1hZGRpbWFoZXNoMTExQGdtYWlsLmNvbSIsImlhdCI6MTcxMzkzOTE4OCwiZXhwIjoxNzE2NTMxMTg4fQ.BVMQyFtOVzmjPKW6Q4OMs4PQqCPVkjTDDiCuH2RqOkE

{
    "email": "test1@gmail.com",
    "password": "12345",
    "fullName": "testing1",
    "mobile": "12345125"
  }
###
DELETE http://localhost:7200/deleteProductFromCart/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haGVzaCBNYWRkaGkiLCJlbWFpbCI6Im1hZGRpbWFoZXNoMTExQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2MzkwMiwiZXhwIjoxNzE2NjU1OTAyfQ.J7DGD2F-coPudhYwsAZGO3Ym1DsjKebbVmBU1DW7nPE


###
GET http://localhost:7200/createProductTable
Content-Type: application/json

###
GET http://localhost:7200/addCol
Content-Type: application/json

###
POST http://localhost:7200/addProductsIntoProductsTable
Content-Type: application/json

{
    
}
###
GET http://localhost:7200/search?q=tomato
Content-Type: application/json

###
GET http://localhost:7200/categories/
Content-Type: application/json



###

POST https://veggie-bazaar.vercel.app/login
Content-Type: application/json

{
   "email": "maddimahesh111@gmail.com",
    "password": "12345"
}

###
POST https://veggie-bazaar-backend-mongodb.vercel.app/addUser
Content-Type: application/json

{
   "email": "test@gmail.com",
    "password": "12345",
    "fullName": "mahesh.m",
    "mobile": "9876543210"
}

### 
GET http://localhost:7200/contact/getMessages/maddimahesh111@gmail.com
Content-Type: application/json

###

POST http://localhost:7200/contact/addMessage
Content-Type: application/json

{
  "email":"maddimahesh111@gmail.com",
  "name":"mahesh Maddhi",
  "subject":"testing",
  "message":"testing 123"
}

###